[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[tool.ruff.lint]
# Enable Pyflakes, pycodestyle, pydocstyle, and isort.
select = ["E", "F", "W", "I", "UP", "PL"]

# Never enforce `E501` (line-too-long), handled by `format`.
# TODO: Refactor complex functions to resolve these ignores
ignore = ["E501", "PLR0911", "PLR0912", "PLR0915"]

[tool.ruff.lint.pydocstyle]
# Use the PEP 257 convention for docstring formatting.
convention = "pep257"

[tool.ruff.lint.mccabe]
# Set the maximum complexity to 10.
max-complexity = 10

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
