version = "0.9.0"

[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

# Exclude problematic or generated files
exclude = ["fix_imports.py"]

# Assume Python 3.9
target-version = "py39"

[tool.ruff.lint]
# Enable Pyflakes, pycodestyle, pydocstyle, and isort.
select = ["E", "F", "W", "I", "UP", "PL"]

# Never enforce `E501` (line-too-long), handled by `format`.
# TODO: Refactor complex functions to resolve these ignores
ignore = ["E501", "PLR0911", "PLR0912", "PLR0915", "PLC0415", "E402"]

[tool.ruff.lint.pydocstyle]
# Use the PEP 257 convention for docstring formatting.
convention = "pep257"

[tool.ruff.lint.mccabe]
# Set the maximum complexity to 10.
max-complexity = 10

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

[dependency-groups]
dev = [
    "mock-firestore>=0.11.0",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "pytest-flask>=1.3.0",
    "pytest-playwright>=0.7.2",
]
