# ruff.toml

# Same as Black.
line-length = 88
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[lint]
# Enable Pyflakes, pycodestyle, pydocstyle, isort, annotations, and McCabe complexity.
select = ["E", "F", "W", "D", "I", "ANN", "C90"]

# Never enforce `E501` (line-too-long), handled by `format`.
ignore = ["E501"]

[lint.pydocstyle]
# Use the PEP 257 convention for docstring formatting.
convention = "pep257"

[lint.mccabe]
# Set the maximum complexity to 10.
max-complexity = 10

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
